import { CropData, MarketData, FarmerReport } from '@/types';

// Mock crop database
export const cropDatabase: Record<string, CropData> = {
  wheat: {
    cropName: 'Wheat',
    scientificName: 'Triticum aestivum',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained loamy soil with pH 6.0-7.5',
    climateRequirements: 'Cool climate during growth, warm during harvest. Temperature: 10-25°C',
    averageYield: '3.5-4.5 tonnes per hectare',
    waterRequirements: '450-650mm during crop cycle',
    harvestTime: 'March to April',
  },
  rice: {
    cropName: 'Rice',
    scientificName: 'Oryza sativa',
    growingSeason: 'June to November (Kharif crop)',
    soilRequirements: 'Clay or clay loam soil with good water retention. pH 5.5-7.0',
    climateRequirements: 'Tropical climate with high humidity. Temperature: 20-35°C',
    averageYield: '4.0-6.0 tonnes per hectare',
    waterRequirements: '1200-1800mm during crop cycle',
    harvestTime: 'October to November',
  },
  soybean: {
    cropName: 'Soybean',
    scientificName: 'Glycine max',
    growingSeason: 'June to October (Kharif crop)',
    soilRequirements: 'Well-drained fertile loamy soil. pH 6.0-7.0',
    climateRequirements: 'Warm and moist climate. Temperature: 20-30°C',
    averageYield: '2.0-3.0 tonnes per hectare',
    waterRequirements: '450-700mm during crop cycle',
    harvestTime: 'September to October',
  },
  corn: {
    cropName: 'Corn (Maize)',
    scientificName: 'Zea mays',
    growingSeason: 'June to September (Kharif) or February to May (Spring)',
    soilRequirements: 'Deep, fertile, well-drained soil. pH 5.8-7.0',
    climateRequirements: 'Warm climate with adequate moisture. Temperature: 21-30°C',
    averageYield: '5.0-8.0 tonnes per hectare',
    waterRequirements: '500-800mm during crop cycle',
    harvestTime: 'August to September or May to June',
  },
  cotton: {
    cropName: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    growingSeason: 'April to November',
    soilRequirements: 'Black cotton soil or deep alluvial soil. pH 5.5-8.0',
    climateRequirements: 'Warm climate with clear sunny days. Temperature: 21-35°C',
    averageYield: '1.5-2.5 tonnes per hectare (lint)',
    waterRequirements: '700-1200mm during crop cycle',
    harvestTime: 'October to January',
  },
  sugarcane: {
    cropName: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    growingSeason: 'February to January (12-18 months crop)',
    soilRequirements: 'Deep, well-drained loamy soil. pH 6.0-8.0',
    climateRequirements: 'Tropical and subtropical climate. Temperature: 20-35°C',
    averageYield: '70-100 tonnes per hectare',
    waterRequirements: '1500-2500mm during crop cycle',
    harvestTime: 'November to April',
  },
  potato: {
    cropName: 'Potato',
    scientificName: 'Solanum tuberosum',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained sandy loam soil. pH 5.0-6.5',
    climateRequirements: 'Cool climate with moderate temperature. Temperature: 15-25°C',
    averageYield: '20-30 tonnes per hectare',
    waterRequirements: '500-700mm during crop cycle',
    harvestTime: 'January to March',
  },
  tomato: {
    cropName: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    growingSeason: 'Year-round in suitable climates',
    soilRequirements: 'Well-drained fertile loamy soil. pH 6.0-7.0',
    climateRequirements: 'Warm climate with moderate humidity. Temperature: 18-27°C',
    averageYield: '25-40 tonnes per hectare',
    waterRequirements: '400-600mm during crop cycle',
    harvestTime: '60-90 days after transplanting',
  },
  onion: {
    cropName: 'Onion',
    scientificName: 'Allium cepa',
    growingSeason: 'November to May (Rabi) or June to October (Kharif)',
    soilRequirements: 'Well-drained sandy loam to clay loam. pH 6.0-7.5',
    climateRequirements: 'Cool climate for bulb development. Temperature: 13-24°C',
    averageYield: '20-30 tonnes per hectare',
    waterRequirements: '350-500mm during crop cycle',
    harvestTime: 'April to May or October to November',
  },
  mustard: {
    cropName: 'Mustard',
    scientificName: 'Brassica juncea',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained sandy loam to clay loam. pH 6.0-7.5',
    climateRequirements: 'Cool and dry climate. Temperature: 10-25°C',
    averageYield: '1.0-1.5 tonnes per hectare',
    waterRequirements: '250-400mm during crop cycle',
    harvestTime: 'February to March',
  },
  // Additional crops from data.gov.in
  maize: {
    cropName: 'Maize',
    scientificName: 'Zea mays',
    growingSeason: 'June to September (Kharif) or February to May (Spring)',
    soilRequirements: 'Deep, fertile, well-drained soil. pH 5.8-7.0',
    climateRequirements: 'Warm climate with adequate moisture. Temperature: 21-30°C',
    averageYield: '5.0-8.0 tonnes per hectare',
    waterRequirements: '500-800mm during crop cycle',
    harvestTime: 'August to September or May to June',
  },
  groundnut: {
    cropName: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    growingSeason: 'June to October (Kharif) or January to May (Rabi)',
    soilRequirements: 'Well-drained sandy loam soil. pH 6.0-6.5',
    climateRequirements: 'Warm climate with moderate rainfall. Temperature: 25-30°C',
    averageYield: '1.5-2.5 tonnes per hectare',
    waterRequirements: '500-700mm during crop cycle',
    harvestTime: 'October to November or April to May',
  },
  gram: {
    cropName: 'Gram (Chickpea)',
    scientificName: 'Cicer arietinum',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-8.0',
    climateRequirements: 'Cool and dry climate. Temperature: 15-25°C',
    averageYield: '1.0-1.5 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: 'February to March',
  },
  chana: {
    cropName: 'Chana (Bengal Gram)',
    scientificName: 'Cicer arietinum',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-8.0',
    climateRequirements: 'Cool and dry climate. Temperature: 15-25°C',
    averageYield: '1.0-1.5 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: 'February to March',
  },
  arhar: {
    cropName: 'Arhar (Pigeon Pea)',
    scientificName: 'Cajanus cajan',
    growingSeason: 'June to February (Kharif crop)',
    soilRequirements: 'Well-drained loamy soil. pH 5.0-7.0',
    climateRequirements: 'Warm and semi-arid climate. Temperature: 18-30°C',
    averageYield: '1.0-1.5 tonnes per hectare',
    waterRequirements: '600-700mm during crop cycle',
    harvestTime: 'December to February',
  },
  moong: {
    cropName: 'Moong (Green Gram)',
    scientificName: 'Vigna radiata',
    growingSeason: 'July to October (Kharif) or March to June (Summer)',
    soilRequirements: 'Well-drained sandy loam soil. pH 6.5-7.5',
    climateRequirements: 'Warm climate with moderate rainfall. Temperature: 25-35°C',
    averageYield: '0.8-1.2 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: '60-70 days after sowing',
  },
  urad: {
    cropName: 'Urad (Black Gram)',
    scientificName: 'Vigna mungo',
    growingSeason: 'July to October (Kharif) or March to June (Summer)',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.5',
    climateRequirements: 'Warm and humid climate. Temperature: 25-35°C',
    averageYield: '0.8-1.2 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: '70-90 days after sowing',
  },
  bajra: {
    cropName: 'Bajra (Pearl Millet)',
    scientificName: 'Pennisetum glaucum',
    growingSeason: 'June to September (Kharif crop)',
    soilRequirements: 'Light sandy to loamy soil. pH 6.0-7.0',
    climateRequirements: 'Hot and dry climate. Temperature: 25-35°C',
    averageYield: '1.5-2.5 tonnes per hectare',
    waterRequirements: '350-500mm during crop cycle',
    harvestTime: 'September to October',
  },
  jowar: {
    cropName: 'Jowar (Sorghum)',
    scientificName: 'Sorghum bicolor',
    growingSeason: 'June to October (Kharif) or October to February (Rabi)',
    soilRequirements: 'Well-drained clay loam soil. pH 5.5-8.5',
    climateRequirements: 'Warm and dry climate. Temperature: 25-32°C',
    averageYield: '2.0-3.0 tonnes per hectare',
    waterRequirements: '400-600mm during crop cycle',
    harvestTime: 'September to October or February to March',
  },
  barley: {
    cropName: 'Barley',
    scientificName: 'Hordeum vulgare',
    growingSeason: 'October to April (Rabi crop)',
    soilRequirements: 'Well-drained loamy to clay loam soil. pH 6.0-8.0',
    climateRequirements: 'Cool climate with low humidity. Temperature: 12-25°C',
    averageYield: '2.5-4.0 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: 'March to April',
  },
  sunflower: {
    cropName: 'Sunflower',
    scientificName: 'Helianthus annuus',
    growingSeason: 'Year-round in suitable climates',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.5',
    climateRequirements: 'Warm climate with full sun. Temperature: 20-30°C',
    averageYield: '1.5-2.0 tonnes per hectare',
    waterRequirements: '400-600mm during crop cycle',
    harvestTime: '90-100 days after sowing',
  },
  banana: {
    cropName: 'Banana',
    scientificName: 'Musa acuminata',
    growingSeason: 'Year-round (Perennial)',
    soilRequirements: 'Deep, rich loamy soil. pH 6.5-7.5',
    climateRequirements: 'Tropical humid climate. Temperature: 20-35°C',
    averageYield: '30-50 tonnes per hectare',
    waterRequirements: '1500-2000mm per year',
    harvestTime: '10-12 months after planting',
  },
  mango: {
    cropName: 'Mango',
    scientificName: 'Mangifera indica',
    growingSeason: 'Flowering: Dec-Feb, Fruiting: Apr-Jul',
    soilRequirements: 'Deep, well-drained alluvial soil. pH 5.5-7.5',
    climateRequirements: 'Tropical to subtropical climate. Temperature: 24-30°C',
    averageYield: '8-10 tonnes per hectare',
    waterRequirements: '1000-1500mm per year',
    harvestTime: 'April to July',
  },
  apple: {
    cropName: 'Apple',
    scientificName: 'Malus domestica',
    growingSeason: 'Flowering: Mar-Apr, Fruiting: Aug-Oct',
    soilRequirements: 'Well-drained loamy soil. pH 5.5-6.5',
    climateRequirements: 'Temperate climate with chilling requirement. Temperature: 4-24°C',
    averageYield: '15-25 tonnes per hectare',
    waterRequirements: '800-1000mm per year',
    harvestTime: 'August to October',
  },
  orange: {
    cropName: 'Orange',
    scientificName: 'Citrus sinensis',
    growingSeason: 'Year-round (Perennial)',
    soilRequirements: 'Well-drained loamy soil. pH 5.5-7.5',
    climateRequirements: 'Subtropical to tropical climate. Temperature: 15-30°C',
    averageYield: '20-30 tonnes per hectare',
    waterRequirements: '1000-1200mm per year',
    harvestTime: 'November to March',
  },
  grapes: {
    cropName: 'Grapes',
    scientificName: 'Vitis vinifera',
    growingSeason: 'Pruning: Jan-Feb, Harvest: Mar-May',
    soilRequirements: 'Well-drained sandy loam soil. pH 6.5-7.5',
    climateRequirements: 'Subtropical climate with hot dry summer. Temperature: 15-40°C',
    averageYield: '20-30 tonnes per hectare',
    waterRequirements: '500-700mm per year',
    harvestTime: 'March to May',
  },
  cabbage: {
    cropName: 'Cabbage',
    scientificName: 'Brassica oleracea var. capitata',
    growingSeason: 'September to February',
    soilRequirements: 'Well-drained fertile loamy soil. pH 6.0-7.5',
    climateRequirements: 'Cool and humid climate. Temperature: 15-21°C',
    averageYield: '30-50 tonnes per hectare',
    waterRequirements: '380-500mm during crop cycle',
    harvestTime: '90-120 days after transplanting',
  },
  cauliflower: {
    cropName: 'Cauliflower',
    scientificName: 'Brassica oleracea var. botrytis',
    growingSeason: 'September to March',
    soilRequirements: 'Well-drained sandy loam to clay loam. pH 6.0-7.0',
    climateRequirements: 'Cool and moist climate. Temperature: 15-20°C',
    averageYield: '20-30 tonnes per hectare',
    waterRequirements: '400-500mm during crop cycle',
    harvestTime: '90-120 days after transplanting',
  },
  brinjal: {
    cropName: 'Brinjal (Eggplant)',
    scientificName: 'Solanum melongena',
    growingSeason: 'Year-round in tropical areas',
    soilRequirements: 'Well-drained fertile loamy soil. pH 5.5-6.5',
    climateRequirements: 'Warm and humid climate. Temperature: 22-30°C',
    averageYield: '20-40 tonnes per hectare',
    waterRequirements: '400-600mm during crop cycle',
    harvestTime: '60-80 days after transplanting',
  },
  carrot: {
    cropName: 'Carrot',
    scientificName: 'Daucus carota',
    growingSeason: 'August to November (main season)',
    soilRequirements: 'Deep, loose sandy loam soil. pH 6.0-6.8',
    climateRequirements: 'Cool climate. Temperature: 15-20°C',
    averageYield: '25-35 tonnes per hectare',
    waterRequirements: '350-400mm during crop cycle',
    harvestTime: '100-120 days after sowing',
  },
  peas: {
    cropName: 'Peas',
    scientificName: 'Pisum sativum',
    growingSeason: 'October to March (Rabi crop)',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.5',
    climateRequirements: 'Cool climate. Temperature: 10-18°C',
    averageYield: '8-12 tonnes per hectare (green pods)',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: '60-90 days after sowing',
  },
  garlic: {
    cropName: 'Garlic',
    scientificName: 'Allium sativum',
    growingSeason: 'October to February',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.5',
    climateRequirements: 'Cool and dry climate. Temperature: 12-24°C',
    averageYield: '10-15 tonnes per hectare',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: 'April to May',
  },
  ginger: {
    cropName: 'Ginger',
    scientificName: 'Zingiber officinale',
    growingSeason: 'March to August (planting)',
    soilRequirements: 'Well-drained sandy loam soil. pH 5.5-6.5',
    climateRequirements: 'Warm and humid climate. Temperature: 25-30°C',
    averageYield: '15-25 tonnes per hectare',
    waterRequirements: '1500-2000mm during crop cycle',
    harvestTime: 'December to February',
  },
  turmeric: {
    cropName: 'Turmeric',
    scientificName: 'Curcuma longa',
    growingSeason: 'April to June (planting)',
    soilRequirements: 'Well-drained loamy soil. pH 5.5-7.5',
    climateRequirements: 'Warm and humid climate. Temperature: 20-30°C',
    averageYield: '20-25 tonnes per hectare (fresh)',
    waterRequirements: '1500-2000mm during crop cycle',
    harvestTime: 'January to March',
  },
  chilli: {
    cropName: 'Chilli',
    scientificName: 'Capsicum annuum',
    growingSeason: 'Year-round in suitable climates',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.0',
    climateRequirements: 'Warm and humid climate. Temperature: 20-30°C',
    averageYield: '2-4 tonnes per hectare (dry)',
    waterRequirements: '600-1000mm during crop cycle',
    harvestTime: '75-90 days after transplanting',
  },
  coconut: {
    cropName: 'Coconut',
    scientificName: 'Cocos nucifera',
    growingSeason: 'Year-round (Perennial palm)',
    soilRequirements: 'Well-drained sandy loam to clay loam. pH 5.0-8.0',
    climateRequirements: 'Tropical coastal climate. Temperature: 20-32°C',
    averageYield: '10,000-15,000 nuts per hectare per year',
    waterRequirements: '1500-2500mm per year',
    harvestTime: 'Year-round after 6-7 years of planting',
  },
  pepper: {
    cropName: 'Black Pepper',
    scientificName: 'Piper nigrum',
    growingSeason: 'May-June (planting), Year-round',
    soilRequirements: 'Well-drained red laterite soil. pH 4.5-6.5',
    climateRequirements: 'Hot and humid tropical climate. Temperature: 20-30°C',
    averageYield: '2-4 kg per vine per year',
    waterRequirements: '2000-3000mm per year',
    harvestTime: 'December to February',
  },
  cardamom: {
    cropName: 'Cardamom',
    scientificName: 'Elettaria cardamomum',
    growingSeason: 'June-July (planting)',
    soilRequirements: 'Well-drained forest loam soil. pH 5.0-7.5',
    climateRequirements: 'Cool and humid climate. Temperature: 10-35°C',
    averageYield: '100-200 kg per hectare',
    waterRequirements: '1500-4000mm per year',
    harvestTime: 'August to February',
  },
  cumin: {
    cropName: 'Cumin',
    scientificName: 'Cuminum cyminum',
    growingSeason: 'November to December (Rabi crop)',
    soilRequirements: 'Well-drained sandy loam soil. pH 7.0-8.0',
    climateRequirements: 'Cool and dry climate. Temperature: 15-25°C',
    averageYield: '0.4-0.6 tonnes per hectare',
    waterRequirements: '250-350mm during crop cycle',
    harvestTime: 'March to April',
  },
  coriander: {
    cropName: 'Coriander',
    scientificName: 'Coriandrum sativum',
    growingSeason: 'October to February (Rabi crop)',
    soilRequirements: 'Well-drained loamy soil. pH 6.0-7.0',
    climateRequirements: 'Cool and dry climate. Temperature: 15-25°C',
    averageYield: '0.8-1.2 tonnes per hectare (seeds)',
    waterRequirements: '300-400mm during crop cycle',
    harvestTime: 'February to March',
  },
};

// Mock market data generator
export const generateMarketData = (cropName: string): MarketData => {
  const trends: ('up' | 'down' | 'stable')[] = ['up', 'down', 'stable'];
  const demandLevels = ['High', 'Medium', 'Low'];
  const markets = [
    'Punjab', 'Haryana', 'Uttar Pradesh', 'Maharashtra', 
    'Gujarat', 'Madhya Pradesh', 'Rajasthan', 'Karnataka'
  ];

  const basePrice = Math.floor(Math.random() * 3000) + 1500;
  const priceChangeValue = Math.floor(Math.random() * 200) - 100;
  const trend = trends[Math.floor(Math.random() * trends.length)];

  return {
    currentPrice: `₹${basePrice}/quintal`,
    priceChange: `${priceChangeValue > 0 ? '+' : ''}${priceChangeValue}`,
    priceTrend: trend,
    demandLevel: demandLevels[Math.floor(Math.random() * demandLevels.length)],
    topMarkets: markets.sort(() => Math.random() - 0.5).slice(0, 4),
  };
};

// Mock farmer reports generator
export const generateFarmerReports = (cropName: string): FarmerReport[] => {
  const regions = ['Punjab', 'Maharashtra', 'Karnataka', 'Gujarat', 'Uttar Pradesh'];
  const sentiments: ('positive' | 'neutral' | 'negative')[] = ['positive', 'neutral', 'negative'];
  const pestIssues = [
    'Minor aphid infestation',
    'No significant pest issues',
    'Moderate fungal infection',
    'Locust threat in some areas',
    'Controlled pest environment',
  ];
  const weatherImpacts = [
    'Favorable rainfall conditions',
    'Drought stress in some regions',
    'Excessive rainfall causing waterlogging',
    'Ideal temperature range maintained',
    'Heat stress affecting growth',
  ];
  const comments = [
    'Expecting good harvest this season',
    'Yield slightly below expectations due to weather',
    'Government support has been helpful',
    'Need better irrigation facilities',
    'Market prices are encouraging',
    'Facing challenges with input costs',
  ];

  return regions.slice(0, 3 + Math.floor(Math.random() * 2)).map((region, index) => ({
    region,
    reportDate: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    yieldRating: Math.floor(Math.random() * 3) + 3,
    pestIssues: pestIssues[Math.floor(Math.random() * pestIssues.length)],
    weatherImpact: weatherImpacts[Math.floor(Math.random() * weatherImpacts.length)],
    overallSentiment: sentiments[Math.floor(Math.random() * sentiments.length)],
    comments: comments[Math.floor(Math.random() * comments.length)],
  }));
};
